package UI;

import DatabaseConnection.DatabaseEmployeeDAO;
import DatabaseConnection.DatabaseUserDAO.DatabaseException;
import DatabaseConnection.DatabaseUtility;
import com.toedter.calendar.JDateChooser;
import entities.Employee;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

public class UpdateEmployeeFrame extends javax.swing.JFrame {

    private CustomTable employeesTable;   
    private int selectedEmployeeId; // Changed from selectedUserId to avoid confusion with method parameter
  

    

    public UpdateEmployeeFrame(CustomTable employeesTable, int employeeId) throws DatabaseException {
        this.employeesTable = employeesTable;
        this.selectedEmployeeId = employeeId;
        initComponents();
        loadDropdownItems();
        setupConfirmButtonAction();
        loadDropdownEmpStatus();
        loadEmployeeDetails(employeeId);
       
        
        
        this.employeesTable = employeesTable; // Initialize usersTable reference
    }

    private void loadDropdownItems() {
    loadItems("supervisors", "SupervisorName", supervisorField);
    loadItems("department", "DepartmentName", departmentField);
    
}

    private void loadItems(String tableName, String columnName, CustomDropdown dropdownField) {
    String[] dropdownItems = DatabaseUtility.fetchDropdownItems(tableName, columnName);
    dropdownField.setItems(dropdownItems);
    }
    
    private void loadDropdownEmpStatus() {
    String[] items = {"Probationary", "Regular"};
    empStatusField.setItems(items);
}
    
   public void loadEmployeeDetails(int employeeId) throws DatabaseException {
        DatabaseEmployeeDAO employeeDAO = new DatabaseEmployeeDAO();
        Employee employee = employeeDAO.getEmployeeById(employeeId);

       
        lastNameField.setText(employee.getLastName());
        firstNameField.setText(employee.getFirstName());
        birthdayField.setSelectedDate(new SimpleDateFormat("yyyy-MM-dd").format(employee.getBirthday()));
        addressField.setText(employee.getAddress());
        phoneNumberField.setText(employee.getPhoneNumber());
        sssNumberField.setText(employee.getSssNumber());
        philhealthNumberField.setText(employee.getPhilhealthNumber());
        tinNumberField.setText(employee.getTinNumber());
        pagibigNumberField.setText(employee.getPagibigNumber());
        empStatusField.setSelectedEmpStatus(employee.getEmpStatus());
        positionField.setText(employee.getPosition());
        supervisorField.setSelectedSupervisor(employee.getSupervisorName());
        departmentField.setSelectedDepartment(employee.getDepartmentName());
        basicSalaryField.setText(String.valueOf(employee.getBasicSalary()));
        riceSubsidyField.setText(String.valueOf(employee.getRiceSubsidy()));
        phoneAllowanceField.setText(String.valueOf(employee.getPhoneAllowance()));
        clothingAllowanceField.setText(String.valueOf(employee.getClothingAllowance()));
        grossSemiMonthlyRateField.setText(String.valueOf(employee.getGrossSemiMonthlyRate()));
        hourlyRateField.setText(String.valueOf(employee.getHourlyRate()));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField3 = new UI.RoundedTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        confirmUpdateEmpBtn = new UI.RoundedButton();
        jLabel5 = new javax.swing.JLabel();
        lastNameField = new UI.RoundedTextField();
        jLabel6 = new javax.swing.JLabel();
        empStatusField = new UI.CustomDropdown();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        firstNameField = new UI.RoundedTextField();
        jLabel7 = new javax.swing.JLabel();
        addressField = new UI.RoundedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phoneNumberField = new UI.RoundedTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        positionField = new UI.RoundedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        supervisorField = new UI.CustomDropdown();
        departmentField = new UI.CustomDropdown();
        jLabel18 = new javax.swing.JLabel();
        sssNumberField = new UI.RoundedTextField();
        jLabel19 = new javax.swing.JLabel();
        pagibigNumberField = new UI.RoundedTextField();
        jLabel20 = new javax.swing.JLabel();
        philhealthNumberField = new UI.RoundedTextField();
        jLabel21 = new javax.swing.JLabel();
        tinNumberField = new UI.RoundedTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        basicSalaryField = new UI.RoundedTextField();
        jLabel24 = new javax.swing.JLabel();
        grossSemiMonthlyRateField = new UI.RoundedTextField();
        jLabel25 = new javax.swing.JLabel();
        hourlyRateField = new UI.RoundedTextField();
        jLabel26 = new javax.swing.JLabel();
        riceSubsidyField = new UI.RoundedTextField();
        jLabel27 = new javax.swing.JLabel();
        phoneAllowanceField = new UI.RoundedTextField();
        jLabel28 = new javax.swing.JLabel();
        clothingAllowanceField = new UI.RoundedTextField();
        birthdayField = new UI.CalendarPicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        usernameField3.setForeground(new java.awt.Color(204, 204, 204));

        jLabel9.setText("First Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(471, 349));
        setPreferredSize(new java.awt.Dimension(650, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 1000));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ADD NEW EMPLOYEE");

        confirmUpdateEmpBtn.setBorder(null);
        confirmUpdateEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmUpdateEmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-add-user-24.png"))); // NOI18N
        confirmUpdateEmpBtn.setText("Confirm");
        confirmUpdateEmpBtn.setBorderColor(new java.awt.Color(0, 102, 204));
        confirmUpdateEmpBtn.setBorderPainted(false);
        confirmUpdateEmpBtn.setColor(new java.awt.Color(4, 14, 163));
        confirmUpdateEmpBtn.setColorClick(new java.awt.Color(0, 102, 204));
        confirmUpdateEmpBtn.setColorOver(new java.awt.Color(0, 102, 204));
        confirmUpdateEmpBtn.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        confirmUpdateEmpBtn.setRadius(30);
        confirmUpdateEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpdateEmpBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Last Name");

        lastNameField.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setText("Date of Birth");

        empStatusField.setForeground(new java.awt.Color(204, 204, 204));
        empStatusField.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Personal Information");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        firstNameField.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setText("First Name");

        addressField.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setText("Address");

        jLabel10.setText("Phone Number");

        phoneNumberField.setForeground(new java.awt.Color(51, 51, 51));
        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Employment Information");

        jLabel11.setText("Position");

        positionField.setForeground(new java.awt.Color(51, 51, 51));
        positionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Employment Status");

        jLabel13.setText("Supervisor");

        jLabel14.setText("Department");

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Goverment ID Numbers");

        supervisorField.setForeground(new java.awt.Color(204, 204, 204));
        supervisorField.setToolTipText("");

        departmentField.setForeground(new java.awt.Color(204, 204, 204));
        departmentField.setToolTipText("");

        jLabel18.setText("SSS Number");

        sssNumberField.setForeground(new java.awt.Color(51, 51, 51));
        sssNumberField.setToolTipText("Format eg. 12-1234567-1");
        sssNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssNumberFieldActionPerformed(evt);
            }
        });

        jLabel19.setText("Pagibig Number");

        pagibigNumberField.setForeground(new java.awt.Color(51, 51, 51));
        pagibigNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigNumberFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("Philhealth Number");

        philhealthNumberField.setForeground(new java.awt.Color(51, 51, 51));
        philhealthNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthNumberFieldActionPerformed(evt);
            }
        });

        jLabel21.setText("TIN");

        tinNumberField.setForeground(new java.awt.Color(51, 51, 51));
        tinNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinNumberFieldActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Salary Information");

        jLabel23.setText("Basic Salary");

        basicSalaryField.setForeground(new java.awt.Color(51, 51, 51));
        basicSalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSalaryFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("Gross Semi-monthly Rate");

        grossSemiMonthlyRateField.setForeground(new java.awt.Color(51, 51, 51));
        grossSemiMonthlyRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossSemiMonthlyRateFieldActionPerformed(evt);
            }
        });

        jLabel25.setText("Hourly Rate");

        hourlyRateField.setForeground(new java.awt.Color(51, 51, 51));
        hourlyRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateFieldActionPerformed(evt);
            }
        });

        jLabel26.setText("Rice Subsidy");

        riceSubsidyField.setForeground(new java.awt.Color(51, 51, 51));
        riceSubsidyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceSubsidyFieldActionPerformed(evt);
            }
        });

        jLabel27.setText("Phone Allowance");

        phoneAllowanceField.setForeground(new java.awt.Color(51, 51, 51));
        phoneAllowanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneAllowanceFieldActionPerformed(evt);
            }
        });

        jLabel28.setText("Clothing Allowance");

        clothingAllowanceField.setForeground(new java.awt.Color(51, 51, 51));
        clothingAllowanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingAllowanceFieldActionPerformed(evt);
            }
        });

        birthdayField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Format : 12-1234567-1");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Format: 12 digit numbers");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Format: 123-123-123-123");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Format: 12 digit numbers");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("Format: 123-123-123");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(departmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(positionField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(65, 65, 65)
                                                        .addComponent(jLabel13))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(empStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(supervisorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(16, 16, 16))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(281, 281, 281))
                                                    .addComponent(addressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(19, 19, 19)
                                                        .addComponent(jLabel10))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel30))
                                                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel14)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(sssNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pagibigNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(philhealthNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20)))
                                    .addComponent(jLabel22)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(basicSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(grossSemiMonthlyRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hourlyRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(riceSubsidyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(phoneAllowanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel27))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(clothingAllowanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel28)))
                                            .addComponent(confirmUpdateEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tinNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel17)))
                            .addComponent(jLabel2))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(36, 36, 36)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supervisorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(empStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(philhealthNumberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sssNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(pagibigNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinNumberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(1, 1, 1)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hourlyRateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(basicSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(grossSemiMonthlyRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clothingAllowanceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(riceSubsidyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(phoneAllowanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(confirmUpdateEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void positionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionFieldActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void confirmUpdateEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateEmpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmUpdateEmpBtnActionPerformed

    private void sssNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssNumberFieldActionPerformed

    private void pagibigNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagibigNumberFieldActionPerformed

    private void philhealthNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philhealthNumberFieldActionPerformed

    private void tinNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinNumberFieldActionPerformed

    private void basicSalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicSalaryFieldActionPerformed

    private void grossSemiMonthlyRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossSemiMonthlyRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossSemiMonthlyRateFieldActionPerformed

    private void hourlyRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateFieldActionPerformed

    private void riceSubsidyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceSubsidyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceSubsidyFieldActionPerformed

    private void phoneAllowanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneAllowanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneAllowanceFieldActionPerformed

    private void clothingAllowanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingAllowanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothingAllowanceFieldActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.RoundedTextField addressField;
    private UI.RoundedTextField basicSalaryField;
    private UI.CalendarPicker birthdayField;
    private UI.RoundedTextField clothingAllowanceField;
    private UI.RoundedButton confirmUpdateEmpBtn;
    private UI.CustomDropdown departmentField;
    private UI.CustomDropdown empStatusField;
    private UI.RoundedTextField firstNameField;
    private UI.RoundedTextField grossSemiMonthlyRateField;
    private UI.RoundedTextField hourlyRateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private UI.RoundedTextField lastNameField;
    private UI.RoundedTextField pagibigNumberField;
    private UI.RoundedTextField philhealthNumberField;
    private UI.RoundedTextField phoneAllowanceField;
    private UI.RoundedTextField phoneNumberField;
    private UI.RoundedTextField positionField;
    private UI.RoundedTextField riceSubsidyField;
    private UI.RoundedTextField sssNumberField;
    private UI.CustomDropdown supervisorField;
    private UI.RoundedTextField tinNumberField;
    private UI.RoundedTextField usernameField3;
    // End of variables declaration//GEN-END:variables

   private void setupConfirmButtonAction() {
        confirmUpdateEmpBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    updateEmployee();
                } catch (SQLException ex) {
                    Logger.getLogger(UpdateEmployeeFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DatabaseException ex) {
                    Logger.getLogger(UpdateEmployeeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Method to update employee details
    private void updateEmployee() throws SQLException, DatabaseException {
        try {
            int row = employeesTable.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to update.", "No Row Selected", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Retrieve employeeId from the selected row
            String employeeIdStr = employeesTable.getValueAt(row, 0).toString();

            // Fetch current employee details from the database based on employeeId
            DatabaseEmployeeDAO employeeDAO = new DatabaseEmployeeDAO();
            Employee employee = employeeDAO.getEmployeeById(Integer.parseInt(employeeIdStr));

            // New details from the form fields
            String newLastName = lastNameField.getText().trim();
            String newFirstName = firstNameField.getText().trim();
            Date newBirthday = birthdayField.getSelectedDate(); // Get the selected date from CalendarPicker

            if (newBirthday == null) {
                JOptionPane.showMessageDialog(this, "Please select a valid birthday.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String newAddress = addressField.getText().trim();
            String newPhoneNumber = phoneNumberField.getText().trim();
            String newSssNumber = sssNumberField.getText().trim();
            String newPhilhealthNumber = philhealthNumberField.getText().trim();
            String newTinNumber = tinNumberField.getText().trim();
            String newPagibigNumber = pagibigNumberField.getText().trim();
            String newEmpStatus = empStatusField.getSelectedItem().trim();
            String newPosition = positionField.getText().trim();
            String newSupervisorName = supervisorField.getSelectedItem().trim();
            String newDepartmentName = departmentField.getSelectedItem().trim(); 
            double newBasicSalary = Double.parseDouble(basicSalaryField.getText().trim());
            double newRiceSubsidy = Double.parseDouble(riceSubsidyField.getText().trim());
            double newPhoneAllowance = Double.parseDouble(phoneAllowanceField.getText().trim());
            double newClothingAllowance = Double.parseDouble(clothingAllowanceField.getText().trim());
            double newGrossSemiMonthlyRate = Double.parseDouble(grossSemiMonthlyRateField.getText().trim());
            double newHourlyRate = Double.parseDouble(hourlyRateField.getText().trim());

            // Validate formats
            if (!isValidSSSNumber(newSssNumber)) {
                JOptionPane.showMessageDialog(this, "Invalid SSS Number format. Please enter in ##-#######-# format.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return; // Return to allow the user to correct the input
            }

            if (!isValidPhoneNumber(newPhoneNumber)) {
                JOptionPane.showMessageDialog(this, "Invalid Phone Number format. Please enter in ###-###-### format.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return; // Return to allow the user to correct the input
            }
            if (!isValidTinNumber(newTinNumber)) {
                JOptionPane.showMessageDialog(this, "Invalid TIN Number format. Please enter in ###-###-###-### format.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return; // Return to allow the user to correct the input
            }
            if (!isValidPhilhealthNumber(newPhilhealthNumber)) {
                JOptionPane.showMessageDialog(this, "Invalid Philhealth Number format. Please enter a 12-digit number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return; // Return to allow the user to correct the input
            }
            if (!isValidPagibigNumber(newPagibigNumber)) {
                JOptionPane.showMessageDialog(this, "Invalid Pagibig Number format. Please enter a 12-digit number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return; // Return to allow the user to correct the input
            }

            // Check for existing unique fields
            if (!newPhoneNumber.equals(employee.getPhoneNumber()) && employeeDAO.isPhoneNumberExists(newPhoneNumber)) {
                JOptionPane.showMessageDialog(this, "Phone number already exists. Please enter a unique phone number.", "Duplicate Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newSssNumber.equals(employee.getSssNumber()) && employeeDAO.isSSSNumberExists(newSssNumber)) {
                JOptionPane.showMessageDialog(this, "SSS number already exists. Please enter a unique SSS number.", "Duplicate Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newPhilhealthNumber.equals(employee.getPhilhealthNumber()) && employeeDAO.isPhilhealthNumberExists(newPhilhealthNumber)) {
                JOptionPane.showMessageDialog(this, "PhilHealth number already exists. Please enter a unique Philhealth number.", "Duplicate Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newTinNumber.equals(employee.getTinNumber()) && employeeDAO.isTinNumberExists(newTinNumber)) {
                JOptionPane.showMessageDialog(this, "TIN number already exists. Please enter a unique TIN number.", "Duplicate Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newPagibigNumber.equals(employee.getPagibigNumber()) && employeeDAO.isPagibigNumberExists(newPagibigNumber)) {
                JOptionPane.showMessageDialog(this, "PagIbig number already exists. Please enter a unique Pagibig number.", "Duplicate Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update employee in the database
            employeeDAO.updateEmployeeInDatabase(employee.getEmployeeId(), newLastName, newFirstName, new java.sql.Date(newBirthday.getTime()), newAddress, newPhoneNumber, newSssNumber, newPhilhealthNumber, newTinNumber, newPagibigNumber, newEmpStatus, newPosition, newSupervisorName, newDepartmentName, newBasicSalary, newRiceSubsidy, newPhoneAllowance, newClothingAllowance, newGrossSemiMonthlyRate, newHourlyRate);

            // Update employeesTable if needed
            if (employeesTable != null) {
                employeesTable.updateTableData("employees", new String[]{"EmployeeID", "LastName", "FirstName", "Birthday", "Address", "PhoneNumber", "SSSNumber", "PhilHealthNumber", "TinNumber", "PagIbigNumber", "EmpStatus", "Position", "SupervisorID", "DepartmentID", "BasicSalary", "RiceSubsidy", "PhoneAllowance", "ClothingAllowance", "GrossSemiMonthlyRate", "HourlyRate"}, true);
            }

            JOptionPane.showMessageDialog(this, "Employee updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose(); // Close the update frame after successful update
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error updating employee: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Method to validate SSS Number format
    private boolean isValidSSSNumber(String sssNumber) {
        return sssNumber.matches("\\d{2}-\\d{7}-\\d{1}");
    }

    // Method to validate Phone Number format
    private boolean isValidPhoneNumber(String phoneNumber) {
        return phoneNumber.matches("\\d{3}-\\d{3}-\\d{3}");
    }

    // Method to validate Philhealth Number format
    private boolean isValidPhilhealthNumber(String philhealthNumber) {
        return philhealthNumber.matches("\\d{12}");
    }

    // Method to validate TIN Number format
    private boolean isValidTinNumber(String tinNumber) {
        return tinNumber.matches("\\d{3}-\\d{3}-\\d{3}-\\d{3}");
    }

    // Method to validate Pagibig Number format
    private boolean isValidPagibigNumber(String pagibigNumber) {
        return pagibigNumber.matches("\\d{12}");
    }
    }